import type { NextPage } from 'next';
import Head from 'next/head';
import LoginCard from '../src/components/molecules/LoginCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Budget!</h1>

        <p className={styles.description}>Get started by editing logging in!</p>

        <LoginCard
          forgotPasswordLink={'/forgot-password'}
          signUpLink={'/signup'}
          onSubmit={(username: string, password: string) => {
            console.log('CREDS:', username, password);
          }}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
