import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import SignupCard from '../src/components/molecules/SignupCard';
import styles from '../styles/Home.module.css';

declare type UserRegistration = {
  username: string;
  email: string;
  password: string;
};

const SignUp: NextPage = () => {
  const registerUser = async ({
    username,
    email,
    password,
  }: UserRegistration) => {
    axios.post(`${process.env.BASE_API_URL}/users`, {
      //TODO: replace for types?!
      username,
      email,
      password,
    });
    console.log('SNED TO SERVER:', username, email, password);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>My Budget App | Create new account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Create a new account!</h1>

        <p className={styles.description}>jump right in!</p>

        <SignupCard
          loginLink={'/login'}
          onSubmit={(username: string, email: string, password: string) =>
            registerUser({ username, email, password })
          }
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default SignUp;
