import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import SignupCard from '../src/components/molecules/SignupCard';
import styles from '../styles/Home.module.css';

const SignUp: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Budget App | Create new account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Create a new account!</h1>

        <p className={styles.description}>jump right in!</p>

        <SignupCard
          loginLink={'/login'}
          onSubmit={(username: string, email: string, password: string) => {
            axios.post('http://localhost:4000/api/users', {
              username,
              email,
              password,
            });
            console.log('SNED TO SERVER:', username, email, password);
          }}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default SignUp;
